### ISSUE TITLE
Reorganization associated with the Copy status

### ISSUE THREAD

**Issue by tdiak** [InkubatorTieto/melvil#108]
<i>[DL-87] Bug created by Magdalena.Oska</i>
Assignee: Marta Ochowicz
<p>1. Change <tt>available_status</tt> field in Copy model: <br/>
<tt>Boolean</tt> -> <tt>ChoiceType(BookStatus)</tt></p>

<p>2. Update all usages of <tt>available_status</tt> in App</p>

**Comment by wojwarych** [comment]
Issue resolved, see source code for _release/290618_
